recipes-amd/debug-apps: Fix compilation error in debug-apps
Fixes compilation errors
"ERROR: debug-apps-1.0-r0 do_package_qa: QA Issue:
/usr/bin/ubm_fru_update contained in package debug-apps requires
/bin/bash, but no providers found in RDEPENDS_debug-apps? [file-rdeps]
ERROR: debug-apps-1.0-r0 do_package_qa: QA run found fatal errors.
Please consider fixing them."

Signed-off-by: Supreeth Venkatesh <supreeth.venkatesh@amd.com>
Change-Id: I64249a8515b9831a3036d64ca97f8267a65f708b